spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/ecommerce_db?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: duy123!@#
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
